### ISSUE TITLE
Enable SMM

### ISSUE THREAD

**Issue by RoronoaJP** [cadpnq/fo4-smm#1]
Hello,

I try to use your mod since a few days but my problem is that I can't enable it in the game. I'm using Vortex to load my mods in Fallout 4 where everything seems to be enabled then after I launched the game SMM is disabled when I go check in the mods list inside the game. Hope you can help me with that.

Thank you,
Jo

**Comment by cadpnq** [comment]
Are you using the latest version of the game? The behavior you're describing is what happens when you attempt to load a new plugin with an older exe version that cannot support it. My suggestion is to verify that you have game version 1.10.163 and if not update.
